# Generated by Django 5.2 on 2025-12-10 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitment', '0002_rename_notes_interview_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='posted_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
