# Generated by Django 5.2 on 2025-12-09 15:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Permission Group',
                'verbose_name_plural': 'Permission Groups',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('permission_groups', models.ManyToManyField(blank=True, related_name='roles', to='Settings.permissiongroup')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Fine-grained permissions assigned directly to the role.', related_name='settings_roles', to='auth.permission')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Settings.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'verbose_name': 'Role Assignment',
                'verbose_name_plural': 'Role Assignments',
                'unique_together': {('role', 'user')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='custom_roles', through='Settings.RoleAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions bundled under this group.', related_name='settings_permission_groups', to='auth.permission'),
        ),
    ]
