# Generated by Django 5.2 on 2025-10-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
